name: Docker Image CI

on:
  push:
    branches: [ "dependabot/cargo/apis/vara-eth/ethexe-common-c6f1a8a" ]
  pull_request:
    branches: [ "dependabot/cargo/apis/vara-eth/ethexe-common-c6f1a8a" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
